"""THEME_UNIVERSE -- verify a human-curated FUTURE-STATE list against the venue, then seed it.

    AAT_ACCOUNT_ROLE=staging python -m scripts.theme_screen            # verify + write seed
    AAT_ACCOUNT_ROLE=staging python -m scripts.theme_screen --dry      # verify only

WHAT THIS IS, AND IS NOT
========================
Murat's thesis (28 Aug): "energy, robotics and quantum computers are the next
things; raw materials and physical resources become more valuable as demand
grows; embodied robots follow AI, and the money is in the SENSORS AND ACTUATORS,
not the robot brand; batteries, storage, grid, alternative and nuclear energy
matter because oil runs out." That is a HYPOTHESIS GENERATED BY A HUMAN, and the
north star says intuition generates and data adjudicates. This file does not
adjudicate it -- five sessions cannot -- it makes the bet EXECUTABLE and
MEASURABLE: every name is verified tradable on the venue, tagged by theme,
sized by realised volatility, and the account that holds it is a separate
equity curve (`alpha/fleet.py` role `thesis`) so the verdict is a number.

The list is hand-curated. That is survivorship-shaped by construction
(feedback: a hand-picked universe IS survivorship bias) and the receipt says so;
the defence is that this account is graded against IWM and against the other
five accounts, not against its own story.

Fields verified from the venue: tradable, fractionable, has_options attribute,
last close, 20-session median dollar volume, 60-session realised vol. Nothing
here places an order.
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
from datetime import datetime, timedelta, timezone
from pathlib import Path

from alpha import config
from alpha.broker.alpaca import AlpacaPaper

SEED = Path(__file__).resolve().parent.parent / "docs" / "seed" / "universe" / "THEMES_2026-08-28.json"

#: theme -> (symbols, one-line mechanism the human stated)
THEMES: dict[str, tuple[list[str], str]] = {
    "robotics_sensors_actuators": (
        ["SERV", "RR", "OUST", "AEVA", "INVZ", "MVIS", "SYM", "RCAT", "ONDS", "UMAC", "KTOS", "TER", "HSAI"],
        "embodied AI follows LLMs; the picks are the lidar/sensor/actuator suppliers, not the robot brand"),
    "quantum": (
        ["QUBT", "IONQ", "RGTI", "QBTS", "ARQQ", "LAES"],
        "quantum changes the world later; early, pre-revenue, priced on showcases and backlog"),
    "nuclear": (
        ["OKLO", "SMR", "NNE", "LEU", "UEC", "UUUU", "DNN", "NXE", "LTBR", "BWXT"],
        "oil runs out; SMRs and the uranium/enrichment chain are the alternative with policy tailwind"),
    "batteries_storage": (
        ["SLDP", "QS", "ENVX", "EOSE", "FLNC", "AMPX", "MVST", "DFLI", "FREY"],
        "storage is the bottleneck of every alternative-energy build-out; solid-state is the state change"),
    "solar_grid_alt_energy": (
        ["AMSC", "FSLR", "ENPH", "RUN", "ARRY", "NXT", "SHLS", "PLUG", "BE", "FCEL", "POWL"],
        "grid constraints and local-manufacturing policy (the First Solar trade) reprice suppliers"),
    "raw_materials_resources": (
        ["MP", "USAR", "LAC", "PLL", "TMC", "HYMC", "CDE", "HL", "AG", "NAK", "TMQ", "IDR"],
        "more people, more demand; physical things -- rare earths, lithium, silver, land -- appreciate"),
    "murat_book_2026_08_25": (
        ["SLDP", "DKNG", "HUBS", "BHVN", "AMSC", "KYTX", "PRCH", "NTLA", "ABSI", "QUBT", "AARD", "SOC"],
        "the human's live book: compressed optionality -- damaged price, credible better future state, a catalyst"),
}


def _bars(client, sym: str, limit: int = 70) -> list[dict]:
    start = (datetime.now(timezone.utc) - timedelta(days=130)).date().isoformat()
    d = client._request("GET", f"/v2/stocks/{sym}/bars", base=config.data_url(),
                        params={"timeframe": "1Day", "start": start, "limit": limit, "feed": config.stock_feed(),
                                "adjustment": "all"})
    return (d or {}).get("bars") or []


def verify(client, sym: str) -> dict:
    row = {"symbol": sym, "ok": False}
    try:
        a = client._request("GET", f"/v2/assets/{sym}")
    except Exception as exc:                                             # noqa: BLE001
        row["why"] = f"asset: {type(exc).__name__}: {str(exc)[:80]}"
        return row
    row.update({"name": a.get("name"), "exchange": a.get("exchange"), "tradable": bool(a.get("tradable")),
                "shortable": bool(a.get("shortable")), "easy_to_borrow": bool(a.get("easy_to_borrow")),
                "fractionable": bool(a.get("fractionable")),
                "has_options": "has_options" in (a.get("attributes") or [])})
    if not row["tradable"]:
        row["why"] = "not tradable"
        return row
    bars = _bars(client, sym)
    if len(bars) < 25:
        row["why"] = f"only {len(bars)} bars"
        return row
    closes = [float(b["c"]) for b in bars]
    dv = [float(b["c"]) * float(b["v"]) for b in bars[-20:]]
    rets = [math.log(closes[i] / closes[i - 1]) for i in range(1, len(closes)) if closes[i - 1] > 0]
    rv = statistics.pstdev(rets[-60:]) * math.sqrt(252) if len(rets) >= 20 else None
    row.update({"last": closes[-1], "median_dollar_volume_20": statistics.median(dv),
                "realised_vol_60_ann": rv, "ret_20": closes[-1] / closes[-21] - 1 if len(closes) > 21 else None,
                "ret_60": closes[-1] / closes[0] - 1})
    if closes[-1] < 1.0:
        row["why"] = "price < $1"
        return row
    if row["median_dollar_volume_20"] < 2e6:
        row["why"] = "median $vol < $2M"
        return row
    row["ok"] = True
    return row


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true")
    args = ap.parse_args()
    config.load_env()
    client = AlpacaPaper()
    seen: dict[str, dict] = {}
    out_themes = {}
    for theme, (syms, mech) in THEMES.items():
        rows = []
        for s in syms:
            if s not in seen:
                seen[s] = verify(client, s)
            rows.append({**seen[s], "theme": theme})
        out_themes[theme] = {"mechanism": mech, "symbols": syms, "verified": rows}
    print(f"{'sym':<6}{'ok':>3}{'opt':>4}{'short':>6}{'last':>9}{'$vol(M)':>9}{'rv60':>7}{'r20':>7}  theme / why")
    for s, r in seen.items():
        themes = [t for t, (ss, _) in THEMES.items() if s in ss]
        print(f"{s:<6}{('Y' if r['ok'] else '-'):>3}{('Y' if r.get('has_options') else '-'):>4}"
              f"{('Y' if r.get('shortable') else '-'):>6}{(r.get('last') or 0):>9.2f}"
              f"{(r.get('median_dollar_volume_20') or 0) / 1e6:>9.1f}"
              f"{((r.get('realised_vol_60_ann') or 0) * 100):>6.0f}%{((r.get('ret_20') or 0) * 100):>+6.1f}%"
              f"  {','.join(themes)} {r.get('why', '')}")
    ok = [s for s, r in seen.items() if r["ok"]]
    with_opt = [s for s in ok if seen[s].get("has_options")]
    print(f"\n{len(ok)}/{len(seen)} tradable & liquid; {len(with_opt)} with an option chain: {with_opt}")
    if args.dry:
        return 0
    SEED.parent.mkdir(parents=True, exist_ok=True)
    SEED.write_text(json.dumps({
        "name": "THEMES_2026-08-28", "asof_utc": datetime.now(timezone.utc).isoformat(),
        "author": "murat", "stated_by_human": True,
        "caveat": "hand-curated -> survivorship-shaped by construction; graded vs IWM and vs the other fleet roles",
        "themes": out_themes, "tradable": ok, "with_options": with_opt,
    }, indent=1), encoding="utf-8")
    print(f"seed: {SEED}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
